# Generated by Django 5.2.6 on 2025-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10)),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=50)),
                ('photo_path', models.CharField(max_length=255)),
                ('face_encoding', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['name'],
            },
        ),
    ]
