# Generated by Django 5.2.6 on 2025-09-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
