# Generated by Django 3.2 on 2025-09-08 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel_app', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('enrollment_number', models.CharField(max_length=50, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=255, null=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
