# Generated by Django 5.2.6 on 2025-09-08 05:30

from django.db import migrations
from pymongo import MongoClient
from django.conf import settings
import certifi


def migrate_data_from_mongo_to_postgres(apps, schema_editor):
    # Get the Student model
    Student = apps.get_model('hostel_app', 'Student')
    
    # Check if we should migrate data from MongoDB
    # This can be controlled by an environment variable
    import os
    if os.environ.get('MIGRATE_FROM_MONGO', '').lower() != 'true':
        print("Skipping MongoDB data migration. Set MIGRATE_FROM_MONGO=true to enable.")
        return
    
    # Connect to MongoDB
    try:
        # Try with certifi first
        client = MongoClient(
            settings.MONGO_URI,
            tlsCAFile=certifi.where(),
            serverSelectionTimeoutMS=5000,
            connectTimeoutMS=5000,
            tls=True,
            retryWrites=True,
            w='majority'
        )
        # Test connection
        client.admin.command('ping')
        print("Connected to MongoDB successfully")
    except Exception as e:
        print(f"Connection with certifi failed: {e}")
        try:
            # Try with relaxed SSL settings
            client = MongoClient(
                settings.MONGO_URI,
                tlsAllowInvalidCertificates=True,
                serverSelectionTimeoutMS=5000,
                connectTimeoutMS=5000,
                tls=True,
                retryWrites=True,
                w='majority'
            )
            # Test connection
            client.admin.command('ping')
            print("Connected to MongoDB with relaxed SSL")
        except Exception as e2:
            print(f"Connection with relaxed SSL failed: {e2}")
            # Try without explicit TLS settings
            try:
                client = MongoClient(
                    settings.MONGO_URI,
                    serverSelectionTimeoutMS=5000,
                    connectTimeoutMS=5000,
                    tls=True,
                    retryWrites=True,
                    w='majority'
                )
                # Test connection
                client.admin.command('ping')
                print("Connected to MongoDB without explicit TLS")
            except Exception as e3:
                print(f"All connection attempts failed: {e3}")
                # As a last resort, try with a minimal connection
                try:
                    client = MongoClient(settings.MONGO_URI)
                    client.admin.command('ping')
                    print("Connected to MongoDB with minimal configuration")
                except Exception as e4:
                    print(f"Even minimal connection failed: {e4}")
                    print("Skipping MongoDB data migration due to connection issues")
                    return

    # Get MongoDB collection
    db = client[settings.MONGO_DB_NAME]
    collection = db.students

    # Transfer data
    count = 0
    for doc in collection.find():
        Student.objects.create(
            name=doc.get('name', ''),
            room_number=doc.get('room_number'),
            enrollment_number=doc.get('enrollment_number', ''),
            mobile_number=doc.get('mobile_number'),
            course=doc.get('course'),
            photo_path=doc.get('photo_path'),
            face_encoding=doc.get('face_encoding'),
            created_at=doc.get('created_at')
        )
        count += 1
    
    print(f"Migrated {count} students from MongoDB to PostgreSQL")


def reverse_migrate_data_from_postgres_to_mongo(apps, schema_editor):
    # This is a placeholder for reverse migration
    # In a real scenario, you would implement the reverse logic here
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_student'),
    ]

    operations = [
        migrations.RunPython(migrate_data_from_mongo_to_postgres, reverse_migrate_data_from_postgres_to_mongo),
    ]